theme:
    name: material
    features:
        - navigation.sections
        - header.autohide
    palette:
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github
        logo: material/tooltip-edit-outline
    favicon: _static/favicon.png
    custom_dir: docs/_overrides


site_name: PerturbVI
site_description: The documentation for the PerturbVI software library.
site_url: https://mancusolab.github.io/perturbvi

repo_url: https://github.com/mancusolab/perturbvi
repo_name: mancusolab/perturbvi
edit_uri: ""

strict: true  # Don't allow warnings during the build process

exclude_docs: |
    superpowers/
    _scripts/
    _templates/
    requirements.txt

extra_javascript:
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets:
        base_path:
            - .
            - docs
    - admonition
    - toc:
        permalink: true
        toc_depth: 4

plugins:
    - search    # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mkdocstrings:
        default_handler: python
        enable_inventory: true
        custom_templates: docs/_templates
        handlers:
            python:
                paths: [src]
                import:
                - https://docs.kidger.site/equinox/objects.inv
                - https://docs.kidger.site/jaxtyping/objects.inv
                setup_commands:
                    - import jaxtyping
                    - jaxtyping.set_array_name_format("array")
                    - import typing
                    - typing.Any.__module__ = "builtins"
                load_external_modules: true
                options:
                    preload_modules:
                    - equinox
                    - jaxtyping
                    extensions:
                    - pydantic: {schema: true}
                    - docs/_scripts/extension.py:DynamicDocstrings:
                        paths: [perturbvi.families]
                    # general options
                    allow_inspection: true
                    show_bases: true
                    show_source: false
                    # heading options
                    heading_level: 4
                    show_root_heading: true
                    show_root_full_path: true
                    # members options
                    inherited_members: true
                    members_order: source
                    filters:
                        - "!^_"
                        - "^__init__$"
                    # docstring options
                    show_if_no_docstring: true
                    # signature/type annotation options
                    separate_signature: false
                    annotations_path: brief
                    show_signature_annotations: true

nav:
    - Docs:
        - Home: 'index.md'
        - Workflow: 'workflow.md'
        - Input structure: 'input_structure.md'
        - Cookbook: 'cookbook.md'
        - API: 'api.md'
    - Misc:
        - 'authors.md'
        - 'versions.md'
        - 'license.md'
        - 'conduct.md'
        - 'cite.md'
