from typing import Literal


DEFAULT_BLOCK_SIZE = 2048
DEFAULT_P_PRIOR = 0.1
DEFAULT_TAU = 100.0
DEFAULT_STANDARDIZE = False
DEFAULT_INIT: Literal["random", "pca"] = "pca"
DEFAULT_MAX_ITER = 500
DEFAULT_TOL = 1e-3
DEFAULT_VERBOSE = True
DEFAULT_LEARNING_RATE = 1e-2
DEFAULT_SEED = 0
